theme: noesya-hugo-theme
_merge: deep
params:
  default:
    index:
      taxonomies:
        display: false
  ecosystem: lab
  posts:
    date_format: "2006"
    index:
      layout: list
      options:
        categories: false
        image: false
        subtitle: false
        summary: false
    single:
      meta:
        position: hero
        options:
          authors: true
          dates: true
          published_at: true
          reading_time: false
          share: true
          taxonomies: false
          updated_at: false
          with_labels: false
  share_links:
    enabled: true
    email: true
    facebook: false
    linkedin: true
    mastodon: true
    telegram: true
    twitter: false
    whatsapp: true
